### PR TITLE
Fix Travis CI builds

### PR DESCRIPTION
**Pull request by rgabo**
Play nice with Travis CI's environment and test on all major ruby versions

### CODE REVIEW

**Comment by rgabo** [comment]
@aandrieiev now 1.8.7 compatible :smile:

https://travis-ci.org/sspinc/we-are-hiring/builds/64426320

**Comment by rgabo** [comment]
@aandrieiev please review

**Comment by aandrieiev** [comment]
@rgabo this is definitely going to be a game changer for the whole industry in a long prospective, if not right away! Especially for the people still using Ruby 1.8.7

**Comment by rgabo** [comment]
you should merge if LGTM

**Comment by rgabo** [comment]
can't wait to release it to the wild!

**Pull request merged**
